anviz:
    anviz_ip: "192.168.2.225"
    anviz_port: "44444"
    anviz_users: [2, 8]

serial:
    serial_port: "/dev/ttyUSB0"
    serial_users: []

server:
    server_eth: "any" #"192.168.1.2", or "any"
    server_port: "5010"

actions:
    run: "./script.sh"
